### PR TITLE
#15: adds .prettierrc file for TypeScript/Node.JS files

### PR DESCRIPTION
**Pull request by KenSuenobu**
This adds a .prettierrc file that takes care of initial standards for TypeScript, keeping look and design consistent across the board.

### CODE REVIEW

**Comment by rcollette** [comment]
Why not just use the prettier defaults?  In that case you will already be following the will/vote of the masses.

**Comment by KenSuenobu** [comment]
Well, we use most of the defaults; these are just a couple of things we're enforcing.  I'll review the defaults; if they match what I added here, I'll close and remove the branch.  ;)

**Comment by KenSuenobu** [comment]
@rcollette Okay, this reduces the requirements down to one so far.  This keeps strings consistent with Microsoft's TS guidelines.

**Comment by rcollette** [comment]
I like single quotes as well.  I probably type them by default but then Webstorm reformats to double when I save.  I think in one of my older projects I configured single quotes but then just moved to the defaults to "go with the flow".  But perhaps I also saw that the TS contributor guidelines are double quotes (Though they say to ignore them :)

https://github.com/microsoft/TypeScript/wiki/Coding-guidelines#strings

**Comment by KenSuenobu** [comment]
It looks like this is really the only thing to implement - at least, for right now.  TS's own coding guidelines are "do as I say not as I do" ... I still prefer single quotes, and it's been a standard for a while now.  If you're good with this, I'm happy to get this in the API standards as a start.

**Pull request merged**
